name: Run Telegram Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # ඔයා පාවිච්චි කරන Python version එක දාන්න

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          API_URL_TEMPLATE: ${{ secrets.API_URL_TEMPLATE }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py # ඔයාගේ code file එකේ නම දාන්න
